### ISSUE TITLE
expose listener count

### ISSUE THREAD

**Issue by beckend** [smol-rs/event-listener#106]
Using this as a base to create libraries, it's very useful to know the listener count from time to time.

**Comment by notgull** [comment]
This can be done with relative ease on `std` platforms, but on `no_std` it's impossible to know how many listeners are in the last at any given time.

**Comment by beckend** [comment]
Sure, then a feature flag?

**Comment by notgull** [comment]
It sounds fine to restrict it to `std` only. I'll accept a PR

**Comment by beckend** [comment]
PR is online
