### ISSUE TITLE
Is `Event::notify(usize::MAX)` signal safe?

### ISSUE THREAD

**Issue by SteveLauC** [smol-rs/event-listener#141]
## Context

I am trying to build a [crate](https://github.com/SteveLauC/signal-future/tree/main) that provides interfaces similar to the ones provided by [tokio::signal](https://docs.rs/tokio/latest/tokio/signal/index.html) using `event-listener` so that it can be used on runtimes other than Tokio. The problem I am encountering is running unit tests can deadlock sometimes.

### Env

```sh
$ uname -rs
Linux 6.2.9-300.fc38.x86_64

$ cargo --version
cargo 1.78.0 (54d8815d0 2024-03-26)
```

Run tests with multiple threads, there are 6 tests, running with at least 6 threads should make the reproduction easier.
Though it is still not that easy to reproduce with multiple threads, one needs to run the test multiple times to reproduce it:

> I am on Linux, the test with glommio is Linux-only, but the deadlock is reproducible even though this test is disabled.

```sh
$ cargo test # I have 12 cores, so this run uses 12 threads (or 6?)
cargo t
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running unittests src/lib.rs (target/debug/deps/signal_future-8c14674bf6766793)

running 6 tests

test tests::multiple_futures_with_tokio_select has been running for over 60 seconds
test tests::multiple_tasks_waiting_for_same_signal has been running for over 60 seconds
test tests::sigint_with_glommio has been running for over 60 seconds
test tests::sigint_with_monoio has been running for over 60 seconds
test tests::sigint_with_tokio has been running for over 60 seconds
test tests::signt_with_futures_block_on has been running for over 60 seconds
```

### General idea

The general idea is simple, create an `Event` for every signal, and create an `EventListener` when a signal future is constructed (by crate user), in the signal handler, call `.notify(usize::MAX)` to notify all the tasks.

### Some details

The implementation uses [a global vector](https://github.com/SteveLauC/signal-future/blob/ec09b73c11d681fc5709b934cb0e18dc30ab3b43/src/lib.rs#L104-L116) to store the `Events` registered with each signal, it uses the signal number as the index. [Whenever a `SignalFut::new(signal)` is called, it will check if there is a registered event, if not, register one (i.e., store it in the global vector), and call `.listen()` on it to extract the `EventListener`.](https://github.com/SteveLauC/signal-future/blob/ec09b73c11d681fc5709b934cb0e18dc30ab3b43/src/lib.rs#L169-L225), then construct a `SignalFut` using this `EventListener`, then one can `.await` the returned `SigalFut`, [which will poll the inner `EventListener`.](https://github.com/SteveLauC/signal-future/blob/ec09b73c11d681fc5709b934cb0e18dc30ab3b43/src/lib.rs#L227-L234)

The logic of the signal handler is quite simple, [index the corresponding `Event` by the given signal number, then call `.notify(usize::MAX)`.](https://github.com/SteveLauC/signal-future/blob/ec09b73c11d681fc5709b934cb0e18dc30ab3b43/src/lib.rs#L118-L142)

Since the global vector can be concurrently modified by multiple threads, there are cases where multiple threads try to store the `Event` for the same signal, [I use `std::sync::Once` to ensure that ONLY 1 thread will successfully do it.](https://github.com/SteveLauC/signal-future/blob/ec09b73c11d681fc5709b934cb0e18dc30ab3b43/src/lib.rs#L78-L88)

## Possible cause

I am not sure if the issue is related to `event-listerner`, and I think it is more likely due to my buggy implementation. If `Event::notify(usize::MAX)` is not signal-safe, then it might cause the issue, but a glance at the source code didn't show me any operation that is not signal-safe.

## The things I have tried

1. The deadlock does not seem to be introduced by `std::sync::Once` because when I give 6 tests different signals, deadlock can still happen.

## NOTE

Diving into this issue literally means helping me debug my buggy program, which is actually beyond the scope of maintaining this crate, I would appreciate if you guys want to help, but totally understand if you don't want to.

**Comment by SteveLauC** [comment]
Well, I just tried another approach, move `event.notify(usize::MAX)` to another helper thread with the help of the `ctrlc` crate, and it looks like the deadlock is just gone...

**Comment by SteveLauC** [comment]
> Well, I just tried another approach, move `event.notify(usize::MAX)` to another helper thread with the help of the `ctrlc` crate, and it looks like the deadlock is just gone...

I implemented this in the crate, looks like it works pretty well: https://github.com/SteveLauC/signal-future/pull/5

**Comment by notgull** [comment]
None of the functions on `Event` or `EventListener` are signal safe. Most of them lock a mutex, which is an undefined operation in a signal handler and is what's probably causing your deadlock. In addition `Waker` from waking up a listener can run arbitrary code, which isn't signal safe.

**Comment by SteveLauC** [comment]
Thanks for your help!
