### ISSUE TITLE
This seems actually not stable(Dead lock)

### ISSUE THREAD

**Issue by beckend** [smol-rs/event-listener#143]
https://github.com/beckend/event-listener/tree/event_listener_bug

`cargo run --release --example mutex`

https://github.com/beckend/event-listener/blob/event_listener_bug/examples/mutex.rs#L127-L151

It dead locks.

**Comment by notgull** [comment]
Thanks for the report! This seems tricky to replicate, let me see if I can `loom` it.

**Comment by nazar-pc** [comment]
Simple reproduction found in https://github.com/smol-rs/async-lock/issues/91:
```
use event_listener::Event;
use std::pin::pin;

fn main() {
    futures::executor::block_on(async {
        let event = Event::new();

        let listen_a = pin!(event.listen());
        let listen_b = pin!(event.listen());

        drop(listen_a);

        event.notify(1);
        listen_b.await;
    });
}
```
The reason is explained by clippy:
```
warning: call to `std::mem::drop` with a value that does not implement `Drop`. Dropping such a type only extends its contained lifetimes
  --> main.rs:11:9
   |
11 |         drop(listen_a);
   |         ^^^^^^^^^^^^^^
   |
note: argument has type `std::pin::Pin<&mut event_listener::EventListener>`
  --> main.rs:11:14
   |
11 |         drop(listen_a);
   |              ^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#drop_non_drop
   = note: `#[warn(clippy::drop_non_drop)]` on by default
```

No feedback that one of the listeners was dropped.

**Comment by notgull** [comment]
Thanks for the repro! I would like to take some time to set up look tests for this.

**Comment by nazar-pc** [comment]
The test is simple:
```rust


#[test]
fn drop_notified3() {
    let event = Event::new();

    let l1 = pin!(event.listen());
    let mut l2 = pin!(event.listen());

    drop(l1);
    assert_eq!(event.notify(1), 1);
    assert!(is_notified(&mut l2));
}
```

I'm trying to come up with a fix now.

**Comment by nazar-pc** [comment]
Hm... looks like false alarm, it didn't work because `pin!()` extended lifetime of the inner value and that means `Drop::drop` is never called. Back to square one I guess.

**Comment by notgull** [comment]
Quick update on this. I've gotten my hands on hardware that's good enough that I can use it to run Loom tests. Standby while I fully instrument this crate.
