### ISSUE TITLE
Why is the mutex always acquired early in EventListener::poll?

### ISSUE THREAD

**Issue by zserik** [smol-rs/event-listener#20]
https://github.com/smol-rs/event-listener/blob/42a1cac1062dfaca34902ca5c00fb3ba01248bfe/src/lib.rs#L665-L699

Currently, the mutex is always acquired on entering the `EventListener::poll` method. This doesn't seem to be necessary to me, as it is only used in the `State::Notified` case

Edit: ok, it is needed as we modify the linked list. I think it could still be moved after the first match statement, as the pointer isn't dereferenced yet.

**Comment by taiki-e** [comment]
> I think it could still be moved after the first match statement, as the pointer isn't dereferenced yet.

That match statement doesn't seem to include any costly processing, so I don't think moving will actually improve anything.
