### ISSUE TITLE
Double checking and memory ordering in the example can be relaxed?

### ISSUE THREAD

**Issue by ZhennanWu** [smol-rs/event-listener#25]
In the crate example, two checks per loop are used
```rust
let flag = Arc::new(AtomicBool::new(false));
let event = Arc::new(Event::new());

// Spawn a thread that will set the flag after 1 second.
thread::spawn({
    let flag = flag.clone();
    let event = event.clone();
    move || {
        // Wait for a second.
        thread::sleep(Duration::from_secs(1));

        // Set the flag.
        flag.store(true, Ordering::SeqCst);

        // Notify all listeners that the flag has been set.
        // <-- implicit SeqCst fence here
        event.notify(usize::MAX); // <-- access to inner list mutex
    }
});

// Wait until the flag is set.
loop {
    // Check the flag.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Start listening for events.
    let listener = event.listen(); // <-- access to inner list mutex
    // <-- implicit SeqCst fence here

    // Check the flag again after creating the listener.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Wait for a notification and continue the loop.
    listener.wait(); // <-- access to inner list mutex
}
```
But is the first check and the ordering really necessary?

The only possibility for this to hang is when during a single loop, both of those conditions were satisfied:
1. The `listen` mutex access is not visible from `notify`
2. The second `load` returns false

The [reasoning](https://en.cppreference.com/w/cpp/atomic/memory_order)
1. If condition 1 is true, the `Mutex` guarantees `notify` *synchronizes-with* `listen`
2. `notify` *synchronizes-with* `listen` + `listen` *sequences-before* `load` -> `notify` *inter-thread happens-before* `load` (Inter-thread happens-before Rule No.3)
3. `store` *sequences-before* `notify` + `notify` *inter-thread happens-before* `load` -> `store` *inter-thread happens-before* `load` (Inter-thread happens-before Rule No.4)
4. `store` *happens-before* `load` -> `store` is visible side-effect `load`, condition 2 is false. 

So the correctness is guaranteed. As we can see, this correctness guarantee has nothing to do with the first `load` and the memory ordering of the `load`. I think the below code works as well

```rust
let flag = Arc::new(AtomicBool::new(false));
let event = Arc::new(Event::new());

// Spawn a thread that will set the flag after 1 second.
thread::spawn({
    let flag = flag.clone();
    let event = event.clone();
    move || {
        // Wait for a second.
        thread::sleep(Duration::from_secs(1));

        // Set the flag.
        flag.store(true, Ordering::Relaxed);

        // Notify all listeners that the flag has been set.
        // <-- implicit SeqCst fence here
        event.notify(usize::MAX); // <-- access to inner list mutex
    }
});

// Check the flag and see whether we can oppurtunistically bypass listener creation
if !flag.load(Ordering::Relaxed) {
    // Wait until the flag is set.
    loop {
    
        // Start listening for events.
        let listener = event.listen(); // <-- access to inner list mutex
        // <-- implicit SeqCst fence here
    
        // Check the flag again after creating the listener.
        if flag.load(Ordering::Relaxed) {
            break;
        }
    
        // Wait for a notification and continue the loop.
        listener.wait(); // <-- access to inner list mutex
    }
}
```

Perhaps I'm missing something. I'm actually not too sure about some of my assertions above. Or there is more API and engineering concern to this matter?

---
Edit: I realize different usage may impose a different ordering requirement. I'm only using this crate to do grouped task backoff, so not hanging is everything I need. However, if people are doing initialization before `notify` and processing result after the loop, it seems the above code with `Relaxed` still works. (The different `notify` circumstances can cause two different exit routes from the loop, but both routes seem to guarantee visibility)

**Comment by taiki-e** [comment]
This example is so simple and using Relaxed here should not be a problem.
However, we use SeqCst in the example to make it simple. (Explaining optimizing ordering is not the purpose of this example)
