### ISSUE TITLE
[Feature] Getting the number of notified listeners back

### ISSUE THREAD

**Issue by jjl** [smol-rs/event-listener#6]
Hello!

I've just built an RWLock based around a single atomic and now I'm trying to make an async version with eventlistener. For my purposes, simply knowing if any listeners were notified would suffice, but knowing the count seems a logical extension of that.

What do you think?

**Comment by jjl** [comment]
Actually it turns out I don't need this anymore, but I still think it's a good idea for at some point :)

**Comment by stjepang** [comment]
Seems like a reasonable addition to me :)

**Comment by notgull** [comment]
Since we're making breaking changes anyways, it might be worthwhile to add this.
