### ISSUE TITLE
EventListener::new footgun

### ISSUE THREAD

**Issue by zeenix** [smol-rs/event-listener#89]
Copy&pasting from the matrix channel to avoid repeating:

> zeenix: this method takes an Event ref but doesn't actually setup the listener to listen to this event. This seems like a pretty big footgun
> Saltbag: The only other option is to have it insert itself into the list on await, which has its own footguns. It can’t be set up in new since it needs to be pinned.
> zeenix: it's just a very strange and unintuitive api now. I see multiple issues here:
> 
> * `EventListener` existing w/o listening is just strange. The name implies something that's listening.
> * `new` takes a `Event` ref but doesn't listen to the given event.
> * The footgun of awaiting a listener w/o calling listen on it. That state should not be allowed to ever exist.
> 
> If listening require pinning, that should always be implied then. That's the whole point of `EventListener` type. At the very least, new and `EventListener` docs should document all these caveats well.

**Comment by MaxVerevkin** [comment]
> The only other option is to have it insert itself into the list on await, which has its own footguns

Is it because some may assume that listener starts listening immediately after being created when in reality it will listen only when awaited/.wait()'ed?
