### ISSUE TITLE
`EventListener` doesn't implement `UnwindSafe`

### ISSUE THREAD

**Issue by tomaka** [smol-rs/event-listener#95]
I think it's a pretty normal use case to create an `EventListener`, then send the `EventListener` somewhere else, but this somewhere else panics and we want to continue running the program anyway.

Since `Event` itself implements `RefUnwindSafe`, it seems that `EventListener` not implementing `UnwindSafe` is just an overlook?

**Comment by notgull** [comment]
Yes, this was an oversight on my part. I would accept a PR to fix this.
